
const CurrentSongConstants = {
  FETCH_CURRENT_SONG: "FETCH_CURRENT_SONG",
  RECEIVE_CURRENT_SONG: "RECEIVE_CURRENT_SONG",
  CLEAR_CURRENT_SONG: "CLEAR_CURRENT_SONG"
};

module.exports = CurrentSongConstants;
